parcelRequire=function(e,r,n,t){var i="function"==typeof parcelRequire&&parcelRequire,o="function"==typeof require&&require;function u(n,t){if(!r[n]){if(!e[n]){var f="function"==typeof parcelRequire&&parcelRequire;if(!t&&f)return f(n,!0);if(i)return i(n,!0);if(o&&"string"==typeof n)return o(n);var c=new Error("Cannot find module '"+n+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[n][1][r]||r},p.cache={};var l=r[n]=new u.Module(n);e[n][0].call(l.exports,p,l,l.exports,this)}return r[n].exports;function p(e){return u(p.resolve(e))}}u.isParcelRequire=!0,u.Module=function(e){this.id=e,this.bundle=u,this.exports={}},u.modules=e,u.cache=r,u.parent=i,u.register=function(r,n){e[r]=[function(e,r){r.exports=n},{}]};for(var f=0;f<n.length;f++)u(n[f]);if(n.length){var c=u(n[n.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=c:"function"==typeof define&&define.amd?define(function(){return c}):t&&(this[t]=c)}return u}({"uD8j":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.log=e;var o=55,t=40;function e(e,c){var n="-".repeat(o-e.length);if(!c)return console.log("[SW] ".concat(n,"> ").concat(e));if("string"!=typeof c)return console.log("[SW] ".concat(n,"> ").concat(e," "),c);if(c.length<t)return console.log("[SW] ".concat(n,"> ").concat(e," "),c);var r=c.substr(c.length-t,1e3);return console.log("[SW] ".concat(n,"> ").concat(e," "),r)}
},{}],"9fg8":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.cacheFilesAfter=exports.cacheFilesBefore=void 0;var p=["./","../icons/favicon.ico","../icons/favicon-32x32.png","../icons/favicon-16x16.png","../icons/android-chrome-192x192.png","../icons/android-chrome-256x256.png","../icons/android-chrome-512x512.png"];exports.cacheFilesBefore=p;var n=["../js/client.js","../js/app-main.js","../js/sign-main.js","../js/www-main.js","../icons/apple-touch-icon-57x57.png","../icons/apple-touch-icon-60x60.png","../icons/apple-touch-icon-72x72.png","../icons/apple-touch-icon-76x76.png","../icons/apple-touch-icon-114x114.png","../icons/apple-touch-icon-120x120.png","../icons/apple-touch-icon-144x144.png","../icons/apple-touch-icon-152x152.png","../icons/apple-touch-icon-180x180.png","../splash/iphone5_640x1136.png","../splash/iphone6_750x1334.png","../splash/iphonex_1125x2436.png","../splash/iphoneplus_1242x2208.png","../splash/iphonexr_828x1792.png","../splash/iphonexsmax_1242x2688.png","../splash/ipad_1536x2048.png","../splash/ipadpro_1668x2224.png","../splash/ipadpro_1668x2388.png","../splash/ipadpro_2048x2732.png"];exports.cacheFilesAfter=n;
},{}],"iLZu":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.onInstall=l;var e,t=require("./log"),n=require("./cacheFiles");function l(l){l.waitUntil(self.caches.open(self.cacheName).then(function(l){return e=l,(0,t.log)("Installed",e),e.addAll(n.cacheFilesBefore)}).then(function(){return self.skipWaiting()}).then(function(){return e.addAll(n.cacheFilesAfter)}).catch(function(e){(0,t.log)("Install: Error",e)}))}
},{"./log":"uD8j","./cacheFiles":"9fg8"}],"+NfH":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.onActivate=t;var e=require("./log");function t(t){t.waitUntil(self.caches.keys().then(function(t){return(0,e.log)("Activated"),Promise.all(t.filter(function(e){return e!==self.cacheName}).map(function(t){(0,e.log)("Removing cached files from ",t),self.caches.delete(t)}))}).then(function(){return(0,e.log)("Claiming clients"),self.clients.claim()}))}
},{"./log":"uD8j"}],"D5es":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.onFetch=n;var e,t=require("./log");function n(n){var r=n.request.url,c=n.request.destination;switch((0,t.log)("Request Destination",c),c){case"style":case"script":case"manifest":case"document":case"font":case"image":return(0,t.log)("Fetching cache then network",r),void n.respondWith(self.caches.open(self.cacheName).then(function(t){return(e=t).match(n.request)}).then(function(e){return e?((0,t.log)("Serving from cache",e.url),e):self.fetch(n.request)}).then(function(c){return(0,t.log)("Catching",r),n.waitUntil(e.put(n.request,c.clone())),c}).catch(function(e){(0,t.log)("Fetch error",e)}));default:return(0,t.log)("Fetching network only",r),void n.respondWith(self.fetch(n.request))}}
},{"./log":"uD8j"}],"Focm":[function(require,module,exports) {
"use strict";var e=require("./onInstall"),t=require("./onActivate"),n=require("./onFetch");self.cacheName="v1",self.addEventListener("install",e.onInstall),self.addEventListener("activate",t.onActivate),self.addEventListener("fetch",n.onFetch);
},{"./onInstall":"iLZu","./onActivate":"+NfH","./onFetch":"D5es"}]},{},["Focm"], null)